language: c

os:
    - linux

compiler:
    - gcc

env:
  - MPI_IMPL=openmpi
  - CODECOV_TOKEN="7bf8e3f1-2829-4e36-a1ee-853858179bda"

before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - pip install --user codecov

install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL

script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL

after_success:
  - codecov --file coverage/lcov.info --disable search
