language: generic

os:
    - linux

compiler:
    - gcc

env:
  - MPI_IMPL=openmpi

before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT

install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL

script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL

sudo: required

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage build-run.sh &&
  bash <(curl -s https://codecov.io/bash)
