language: c

os:
    - linux

compiler:
    - gcc

env:
  - MPI_IMPL=openmpi

before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT

install:
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL

script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $MPI_IMPL

after_success:
  - bash <(curl -s https://codecov.io/bash)
